
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

/// <reference types="unplugin-vue-router/client" />

import type {
  // type safe route locations
  RouteLocationTypedList,
  RouteLocationResolvedTypedList,
  RouteLocationNormalizedTypedList,
  RouteLocationNormalizedLoadedTypedList,

  // helper types
  // route definitions
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,

  // vue-router extensions
  _RouterTyped,
  RouterLinkTyped,
  NavigationGuard,
  UseLinkFnTyped,
} from 'unplugin-vue-router'

declare module '@vue-router/routes' {
  export interface RouteNamedMap {
    'home': RouteRecordInfo<'home', '/', Record<never, never>, Record<never, never>>,
    'not-found': RouteRecordInfo<'not-found', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    'admin-are-born': RouteRecordInfo<'admin-are-born', '/admin-are-born', Record<never, never>, Record<never, never>>,
    '/blog': RouteRecordInfo<'/blog', '/blog', Record<never, never>, Record<never, never>>,
    'bus-facility': RouteRecordInfo<'bus-facility', '/bus-facility', Record<never, never>, Record<never, never>>,
    'cbse-icse-consultancy': RouteRecordInfo<'cbse-icse-consultancy', '/cbse-icse-consultancy', Record<never, never>, Record<never, never>>,
    '/cbse-on-screen-marking-2026': RouteRecordInfo<'/cbse-on-screen-marking-2026', '/cbse-on-screen-marking-2026', Record<never, never>, Record<never, never>>,
    '/cbse-webinar-2026-exam-guidelines': RouteRecordInfo<'/cbse-webinar-2026-exam-guidelines', '/cbse-webinar-2026-exam-guidelines', Record<never, never>, Record<never, never>>,
    'contact': RouteRecordInfo<'contact', '/contact', Record<never, never>, Record<never, never>>,
    'demotion-principal': RouteRecordInfo<'demotion-principal', '/demotion-principal', Record<never, never>, Record<never, never>>,
    'demotion-vice-principal': RouteRecordInfo<'demotion-vice-principal', '/demotion-vice-principal', Record<never, never>, Record<never, never>>,
    '/importance-of-holistic-education': RouteRecordInfo<'/importance-of-holistic-education', '/importance-of-holistic-education', Record<never, never>, Record<never, never>>,
    'inhouse-intervention': RouteRecordInfo<'inhouse-intervention', '/inhouse-intervention', Record<never, never>, Record<never, never>>,
    'maheshwari-computerisation': RouteRecordInfo<'maheshwari-computerisation', '/maheshwari-computerisation', Record<never, never>, Record<never, never>>,
    'other-consultancy': RouteRecordInfo<'other-consultancy', '/other-consultancy', Record<never, never>, Record<never, never>>,
    'other-page': RouteRecordInfo<'other-page', '/other-page', Record<never, never>, Record<never, never>>,
    'portfolio': RouteRecordInfo<'portfolio', '/portfolio', Record<never, never>, Record<never, never>>,
    'published-papers': RouteRecordInfo<'published-papers', '/published-papers', Record<never, never>, Record<never, never>>,
    'services': RouteRecordInfo<'services', '/services', Record<never, never>, Record<never, never>>,
    'social-responsibility': RouteRecordInfo<'social-responsibility', '/social-responsibility', Record<never, never>, Record<never, never>>,
    'staff-recruitment': RouteRecordInfo<'staff-recruitment', '/staff-recruitment', Record<never, never>, Record<never, never>>,
    'staff-training': RouteRecordInfo<'staff-training', '/staff-training', Record<never, never>, Record<never, never>>,
    'support': RouteRecordInfo<'support', '/support', Record<never, never>, Record<never, never>>,
    'team': RouteRecordInfo<'team', '/team', Record<never, never>, Record<never, never>>,
    '/why-static-ip-required-for-cbse-osm': RouteRecordInfo<'/why-static-ip-required-for-cbse-osm', '/why-static-ip-required-for-cbse-osm', Record<never, never>, Record<never, never>>,
  }
}

declare module '@vue-router' {
  import type { RouteNamedMap } from '@vue-router/routes'

  export type RouterTyped = _RouterTyped<RouteNamedMap>

  /**
   * Type safe version of `RouteLocationNormalized` (the type of `to` and `from` in navigation guards).
   * Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationNormalized<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationNormalizedTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocationNormalizedLoaded` (the return type of `useRoute()`).
   * Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationNormalizedLoaded<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationNormalizedLoadedTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocationResolved` (the returned route of `router.resolve()`).
   * Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationResolved<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationResolvedTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocation` . Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocation<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationTypedList<RouteNamedMap>[Name]

  /**
   * Generate a type safe params for a route location. Requires the name of the route to be passed as a generic.
   */
  export type RouteParams<Name extends keyof RouteNamedMap> = RouteNamedMap[Name]['params']
  /**
   * Generate a type safe raw params for a route location. Requires the name of the route to be passed as a generic.
   */
  export type RouteParamsRaw<Name extends keyof RouteNamedMap> = RouteNamedMap[Name]['paramsRaw']

  export function useRouter(): RouterTyped
  export function useRoute<Name extends keyof RouteNamedMap = keyof RouteNamedMap>(name?: Name): RouteLocationNormalizedLoadedTypedList<RouteNamedMap>[Name]

  export const useLink: UseLinkFnTyped<RouteNamedMap>

  export function onBeforeRouteLeave(guard: NavigationGuard<RouteNamedMap>): void
  export function onBeforeRouteUpdate(guard: NavigationGuard<RouteNamedMap>): void
}

declare module 'vue-router' {
  import type { RouteNamedMap } from '@vue-router/routes'

  export interface TypesConfig {
    beforeRouteUpdate: NavigationGuard<RouteNamedMap>
    beforeRouteLeave: NavigationGuard<RouteNamedMap>

    $route: RouteLocationNormalizedLoadedTypedList<RouteNamedMap>[keyof RouteNamedMap]
    $router: _RouterTyped<RouteNamedMap>

    RouterLink: RouterLinkTyped<RouteNamedMap>
  }
}
